Repository prgrms-web-devcourse-final-project/WEB1_2_Mallangs_BE, pull requests merged in 2024-12, with the labels that each got.

#100 [mod] Board, Category 서비스, 컨트롤러 수정, 이미지 테이블 생성에 따른 관련 수정
  src/main/java/com/mallangs/domain/board/controller/BoardController.java
  src/main/java/com/mallangs/domain/board/controller/CategoryController.java
  src/main/java/com/mallangs/domain/board/dto/request/CategoryCreateRequest.java
  src/main/java/com/mallangs/domain/board/dto/request/CategoryUpdateRequest.java
  src/main/java/com/mallangs/domain/board/dto/request/CommunityCreateRequest.java
  src/main/java/com/mallangs/domain/board/dto/request/CommunityUpdateRequest.java
  src/main/java/com/mallangs/domain/board/dto/request/SightingCreateRequest.java
  src/main/java/com/mallangs/domain/board/dto/request/SightingUpdateRequest.java
  src/main/java/com/mallangs/domain/board/dto/response/AdminCategoryResponse.java
  src/main/java/com/mallangs/domain/board/dto/response/CategoryResponse.java
  src/main/java/com/mallangs/domain/board/dto/response/CommunityDetailResponse.java
  src/main/java/com/mallangs/domain/board/dto/response/SightingDetailResponse.java
  src/main/java/com/mallangs/domain/board/dto/response/SightingListResponse.java
  src/main/java/com/mallangs/domain/board/entity/Board.java
  src/main/java/com/mallangs/domain/board/entity/Category.java
  src/main/java/com/mallangs/domain/board/entity/CategoryLevel.java
  src/main/java/com/mallangs/domain/board/repository/BoardRepository.java
  src/main/java/com/mallangs/domain/board/service/BoardService.java
  src/main/java/com/mallangs/domain/board/service/CategoryService.java
  src/main/java/com/mallangs/global/exception/ErrorCode.java
  src/test/java/com/mallangs/domain/board/repository/BoardRepositoryTest.java
Labels: bug, enhancement

#107 [add] Board 게시판 종류별 전체 게시글 검색 기능 추가
  src/main/java/com/mallangs/domain/board/controller/BoardController.java
  src/main/java/com/mallangs/domain/board/repository/BoardRepository.java
  src/main/java/com/mallangs/domain/board/service/BoardService.java
Labels: add

#109 [mod] Board 검색 엔드포인트 수정
  src/main/java/com/mallangs/domain/board/controller/BoardController.java
Labels: enhancement

#118 Fix/#115 회원 프로필조회 수정 채팅메세지 읽음 수정
  src/main/java/com/mallangs/domain/chat/service/ChatRoomService.java
  src/main/java/com/mallangs/domain/member/controller/MemberUserController.java
  src/main/java/com/mallangs/domain/member/dto/MemberGetResponse.java
  src/main/java/com/mallangs/domain/member/entity/Member.java
  src/main/java/com/mallangs/domain/member/repository/MemberRepository.java
  src/main/java/com/mallangs/domain/member/service/MemberAdminService.java
  src/main/java/com/mallangs/domain/member/service/MemberUserService.java
  src/main/java/com/mallangs/domain/pet/dto/PetMemberProfileResponse.java
  src/main/java/com/mallangs/global/config/SecurityConfig.java
  src/main/java/com/mallangs/global/config/SwaggerConfig.java
Labels: bug

#127 Feature/#123 feat cicd
  .github/workflows/CICD.yml
  .gitignore
  build.gradle
  src/main/java/com/mallangs/domain/article/repository/ArticleRepository.java
  src/main/java/com/mallangs/domain/board/repository/BoardRepository.java
  src/main/java/com/mallangs/domain/board/repository/CategoryRepository.java
  src/main/java/com/mallangs/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/mallangs/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/mallangs/domain/chat/repository/ParticipatedRoomRepository.java
  src/main/java/com/mallangs/domain/comment/repository/CommentRepository.java
  src/main/java/com/mallangs/domain/image/repository/ImageRepository.java
  src/main/java/com/mallangs/domain/member/repository/AddressRepository.java
  src/main/java/com/mallangs/domain/member/repository/MemberRepository.java
  src/main/java/com/mallangs/domain/member/util/UploadUtil.java
Labels: feat

#124 [feat] Image 구현
  src/main/java/com/mallangs/domain/board/controller/BoardController.java
  src/main/java/com/mallangs/domain/chat/dto/response/ChatMessageListResponse.java
  src/main/java/com/mallangs/domain/image/controller/ImageController.java
  src/main/java/com/mallangs/domain/image/dto/ImageDto.java
  src/main/java/com/mallangs/domain/image/dto/ImageResponse.java
  src/main/java/com/mallangs/domain/image/entity/Image.java
  src/main/java/com/mallangs/domain/image/entity/ImageOrder.java
  src/main/java/com/mallangs/domain/image/repository/ImageRepository.java
  src/main/java/com/mallangs/domain/image/service/ImageService.java
  src/main/java/com/mallangs/global/exception/ErrorCode.java
  src/main/java/com/mallangs/global/s3/S3Controller.java
  src/main/java/com/mallangs/global/s3/S3Service.java
Labels: feat

#145 Refactor/회원 api 예외 코드 리펙토링
  src/main/java/com/mallangs/domain/chat/controller/ChatMessageController.java
  src/main/java/com/mallangs/domain/chat/controller/ChatRoomController.java
  src/main/java/com/mallangs/domain/member/controller/MemberUserController.java
  src/main/java/com/mallangs/domain/member/dto/MemberCheckPasswordResponse.java
  src/main/java/com/mallangs/domain/member/dto/MemberCreateRequest.java
  src/main/java/com/mallangs/domain/member/dto/MemberRegisterRequest.java
  src/main/java/com/mallangs/domain/member/service/MemberUserService.java
  src/main/java/com/mallangs/global/exception/ErrorCode.java
Labels: refactor

#148 Refactor/채팅 api 예외 코드 리펙토링
  src/main/java/com/mallangs/domain/chat/controller/ChatMessageController.java
  src/main/java/com/mallangs/domain/chat/dto/response/ChatMessageDeleteSuccessResponse.java
  src/main/java/com/mallangs/domain/chat/dto/response/ChatMessageSuccessResponse.java
  src/main/java/com/mallangs/domain/chat/service/ChatMessageService.java
Labels: refactor

#150 Refactor/주소 api 예외 코드 리펙토링
  src/main/java/com/mallangs/domain/chat/controller/ChatMessageController.java
  src/main/java/com/mallangs/domain/member/controller/AddressController.java
  src/main/java/com/mallangs/domain/member/dto/AddressCreateSuccessResponse.java
  src/main/java/com/mallangs/domain/member/dto/AddressDeleteSuccessResponse.java
  src/main/java/com/mallangs/domain/member/service/AddressService.java
Labels: refactor

#154 [mod] Image 채팅 관련 추가
  src/main/java/com/mallangs/domain/image/controller/ImageController.java
  src/main/java/com/mallangs/domain/image/entity/Image.java
  src/main/java/com/mallangs/domain/image/repository/ImageRepository.java
  src/main/java/com/mallangs/domain/image/service/ImageService.java
  src/main/java/com/mallangs/global/exception/ErrorCode.java
Labels: add

#170 Feature/#168 mod image 응답 구조 변경
  src/main/java/com/mallangs/domain/image/dto/ImageDto.java
  src/main/java/com/mallangs/domain/image/service/ImageService.java
Labels: refactor

#178 [ feat ]review pet service단 테스트 코드 작성
  src/main/java/com/mallangs/domain/pet/dto/PetCreateRequest.java
  src/main/java/com/mallangs/domain/pet/dto/PetResponse.java
  src/main/java/com/mallangs/domain/pet/dto/PetUpdateRequest.java
  src/main/java/com/mallangs/domain/review/dto/ReviewCreateRequest.java
  src/main/java/com/mallangs/domain/review/dto/ReviewUpdateRequest.java
  src/test/java/com/mallangs/domain/pet/service/PetServiceTest.java
  src/test/java/com/mallangs/domain/review/repository/ReviewRepositoryTest.java
  src/test/java/com/mallangs/domain/review/service/ReviewServiceTest.java
Labels: feat

#188 [mod] Board 카테고리 api 수정, SecurityConfig 경로 인가에 category 추가
  src/main/java/com/mallangs/domain/board/controller/CategoryController.java
  src/main/java/com/mallangs/domain/board/repository/CategoryRepository.java
  src/main/java/com/mallangs/domain/board/service/CategoryService.java
  src/main/java/com/mallangs/global/config/SecurityConfig.java
Labels: enhancement

#193 [mod] 관리자 권한 메세지 설정, 로그인 메세지 설정, 게시글 번호 조회 예외 메세지 설정
  src/main/java/com/mallangs/domain/board/controller/BoardController.java
  src/main/java/com/mallangs/domain/board/repository/BoardRepository.java
  src/main/java/com/mallangs/domain/board/service/BoardService.java
  src/main/java/com/mallangs/domain/board/service/CategoryService.java
  src/main/java/com/mallangs/global/exception/ErrorCode.java
Labels: enhancement

#192 [feat] 비회원 엔드포인트
  src/main/java/com/mallangs/domain/pet/controller/PetController.java
  src/main/java/com/mallangs/domain/pet/dto/PetNearbyPageResponse.java
  src/main/java/com/mallangs/domain/pet/dto/PetPageResponse.java
  src/main/java/com/mallangs/domain/pet/service/PetService.java
  src/main/java/com/mallangs/domain/review/controller/ReviewController.java
  src/main/java/com/mallangs/domain/review/dto/ReviewPageResponse.java
  src/main/java/com/mallangs/domain/review/service/ReviewService.java
Labels: feat

#209 [mod] Board api 수정2
  src/main/java/com/mallangs/domain/board/controller/BoardController.java
  src/main/java/com/mallangs/domain/board/dto/response/CommunityListResponse.java
  src/main/java/com/mallangs/domain/board/dto/response/SightingListResponse.java
  src/main/java/com/mallangs/global/jwt/filter/JWTFilter.java
Labels: bug
